services:
  swapswap:
    image: registry.sccs.swarthmore.edu/cs77-s25/swapswap/swapswap:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    #environment:
    #env_file:
    #  - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.swapswap.entrypoints=https"
        - "traefik.http.routers.swapswap.rule=Host(`swapswap.sccs.swarthmore.edu`)"
        - "traefik.http.routers.swapswap.tls=true"
        - "traefik.http.routers.swapswap.tls.certresolver=letsEncrypt"
        - "traefik.http.services.swapswap.loadbalancer.server.port=5000"
    networks:
      - internal
      - traefik

networks:
  internal:

  traefik:
    external: true
