// Listing Model Definition 

/*
Collection: listings
Each document represents a product listing.

Fields:
- id: Auto-generated by Firestore (Primary Key)
- title: string (required, not null)
- description: string (required, not null)
- category: string (required, not null)
- condition: string (required, not null) – values: 'new', 'good', 'fair', 'poor'
- meetingSpot: string (required, not null)
- giveAway: boolean (required, default: false)
- imageURL: string (optional) – URL to image in Firebase Storage
- user_id: string (required, foreign key to users collection)
- date: string (auto-generated YYYY-MM-DD)
*/

// ex of what a document might look like:
export const sampleListing = {
    title: "Nice lamp",
    description: "A working desk lamp, barely used.",
    category: "furniture",
    condition: "good",
    meetingSpot: "Sharples",
    giveAway: false,
    imageURL: "https://firebasestorage.example.com/...",
    user_id: "abc123xyz",
    date: "2025-04-14",
  };
  
export const sampleUser = {
    id: "abc123xyz", // Firestore doc ID
    name: "Carina Olivar",
    email: "carina@example.com",
    bio: "",
    favorites: [], // list of listing IDs (not yet impletmented -- bear with us lol)
  };
  